# Generated by Django 5.2.5 on 2025-08-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0006_alter_profile_branch_alter_profile_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science'), ('AIML', 'Computer Science - Artificial Intelligence & Machine Learning'), ('DS', 'Computer Science - Data Science'), ('EXTC', 'Electronics & Telecommunication'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
