# Generated by Django 5.2.5 on 2025-08-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0007_alter_profile_branch_alter_profile_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_id',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science'), ('AIML', 'Computer Science - Artificial Intelligence & Machine Learning'), ('DS', 'Computer Science - Data Science'), ('EXTC', 'Electronics & Telecommunication'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], max_length=100, null=True),
        ),
    ]
