# Generated by Django 5.2.5 on 2025-08-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0008_rename_email_id_profile_email_alter_profile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_domain',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
