# Generated by Django 5.2.5 on 2025-09-01 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0009_profile_career_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('academic_year', models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26')], max_length=20, null=True)),
                ('semester', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('Internship in Industry', 'Internship in Industry'), ('Internship through APSIT SKILLS Platform', 'Internship through APSIT SKILLS Platform'), ('Internship through AICTE Virtual Internship Platform', 'Internship through AICTE Virtual Internship Platform'), ('PBL', 'PBL'), ('Other', 'Other')], max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
