# Generated by Django 5.2.5 on 2025-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0010_internshippbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippbl',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26')], max_length=20, null=True),
        ),
    ]
