# Generated by Django 5.2.5 on 2025-09-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0013_alter_project_academic_year_sportsculturalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsculturalevent',
            name='venue',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
