# Generated by Django 5.2.5 on 2025-09-06 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0014_alter_sportsculturalevent_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(blank=True, max_length=200, null=True)),
                ('academic_year', models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26')], max_length=20, null=True)),
                ('semester', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=10, null=True)),
                ('level', models.CharField(blank=True, choices=[('College', 'College'), ('University', 'University'), ('District', 'District'), ('State', 'State'), ('National', 'National'), ('International', 'International'), ('Other', 'Other')], max_length=50, null=True)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('prize_won', models.CharField(blank=True, choices=[('Participation', 'Participation'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('Other', 'Other')], max_length=20, null=True)),
                ('amount_won', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('team_members', models.TextField(blank=True, max_length=500, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='other_event_certificates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
