# Generated by Django 5.2.5 on 2025-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0017_paperpublication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperpublication',
            old_name='file',
            new_name='certificate',
        ),
        migrations.AlterField(
            model_name='paperpublication',
            name='authors',
            field=models.TextField(blank=True, help_text='Comma separated list of authors', max_length=255, null=True),
        ),
    ]
