# Generated by Django 5.2.5 on 2025-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0020_longtermgoal_subjectofinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermgoal',
            name='plan',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='longtermgoal',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
