# Generated by Django 5.2.5 on 2025-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0021_alter_longtermgoal_plan_alter_longtermgoal_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermgoal',
            name='plan',
            field=models.CharField(choices=[('Work', 'Work'), ('Post Graduation', 'Post Graduation'), ('Entrepreneurship', 'Entrepreneurship')], max_length=20),
        ),
    ]
