# Generated by Django 5.2.5 on 2025-09-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0022_alter_longtermgoal_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermgoal',
            name='plan',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Post Graduation', 'Post Graduation'), ('Entrepreneurship', 'Entrepreneurship')], max_length=20, null=True),
        ),
    ]
