# Generated by Django 5.2.5 on 2025-09-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0023_alter_longtermgoal_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination', models.CharField(blank=True, choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Diploma', 'Diploma')], max_length=50, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('university_board', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
