# Generated by Django 5.2.5 on 2025-09-11 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0026_meeting_menteeadmin_mentoradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, choices=[('gre', 'GRE'), ('gate', 'GATE'), ('coach', 'GATE/GRE Coaching from College'), ('ent', 'Entrepreneur'), ('hs', 'Higher Studies'), ('place', 'On-campus placements'), ('cyber', 'Cyber Security'), ('robotics', 'Robotics'), ('struct', 'Professional Practices in Structural Engineering'), ('aiml', 'Artificial Intelligence and Machine Learning'), ('iot', 'Internet of Things'), ('athletics', 'Athletics'), ('badminton', 'Badminton'), ('table-tennis', 'Table Tennis'), ('carrom', 'Carrom'), ('chess', 'Chess'), ('kabaddi', 'Kabaddi'), ('cricket', 'Cricket'), ('football', 'Football'), ('tug-of-war', 'Tug of War'), ('dodgeball', 'Dodgeball'), ('volleyball', 'Volleyball'), ('throwball', 'Throwball'), ('dancing', 'Dancing'), ('singing', 'Singing'), ('volunteer', 'Volunteering'), ('leader', 'Leadership'), ('blockchain', 'Blockchain'), ('design', 'Design'), ('mac', 'MAC Racing Club'), ('smart', 'Smart City Club'), ('web', 'Web Development'), ('software-dev', 'Software Development'), ('design-team', 'OJUS Design Team'), ('tech-team', 'OJUS Technical Team'), ('creative-team', 'OJUS Creative Team'), ('photo-team', 'OJUS Photography Team'), ('pub-team', 'OJUS Publicity Team'), ('eve-team', 'OJUS Event Team'), ('gen-sec', 'General Secretary'), ('gs-associate', 'General Secretary Associate'), ('edit-team', 'Editorial Team'), ('creative-media-team', 'Creative Media Team'), ('sports-sec', 'Sports Secretary'), ('cult-sec', 'Cultural Secretary'), ('joint-cult-sec', 'Joint Cultural Secretary'), ('ladies-rep', 'Ladies Representative'), ('joint-ladies-rep', 'Joint Ladies Representative'), ('society', 'Department Level Societies')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'interest')},
            },
        ),
    ]
