# Generated by Django 5.2.5 on 2025-09-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0027_studentinterest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinterest',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='studentinterest',
            unique_together={('student', 'interest')},
        ),
    ]
