# Generated by Django 5.2.5 on 2025-09-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0028_rename_user_studentinterest_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinterest',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='studentinterest',
            unique_together={('user', 'interest')},
        ),
    ]
