# Generated by Django 5.2.5 on 2025-09-11 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0029_rename_student_studentinterest_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinterest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentinterest',
            name='interests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studentinterest',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='studentinterest',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='studentinterest',
            name='user',
        ),
    ]
