# Generated by Django 5.2.5 on 2025-09-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0030_alter_studentinterest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
