# Generated by Django 5.2.5 on 2025-09-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0031_profile_forget_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorMentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_mappings', to='mentee.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_mappings', to='mentee.mentor')),
            ],
            options={
                'unique_together': {('mentor', 'mentee')},
            },
        ),
    ]
