# Generated by Django 5.2.5 on 2025-09-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0032_mentormentee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
