# Generated by Django 5.2.5 on 2025-09-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0033_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to='mentee.mentor'),
        ),
    ]
