# Generated by Django 5.2.5 on 2025-09-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0034_mentee_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormentee',
            name='mentee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_mappings', to='mentee.mentee'),
        ),
    ]
