# Generated by Django 5.2.5 on 2025-09-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0037_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='department',
            field=models.CharField(blank=True, choices=[('CIVIL', 'CIVIL'), ('COMPS', 'COMPUTER SCIENCE'), ('EXTC', 'ELECTRONICS & TELECOMMUNICATION'), ('MECH', 'MECHANICAL'), ('IT', 'INFORMATION TECHNOLOGY'), ('CSE - AIML', 'ARTIFICIAL INTELLIGENCE & MACHINE LEARNING'), ('CSE - DS', 'DATA SCIENCE')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
