# Generated by Django 5.2.5 on 2025-09-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0038_mentor_department_mentor_expertise_mentor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='mentors/'),
        ),
    ]
