# Generated by Django 5.2.5 on 2025-09-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0040_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
