# Generated by Django 5.2.5 on 2025-09-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0041_alter_query_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('moderate', 'Moderate'), ('low', 'Low')], default='low', max_length=10),
        ),
    ]
