# Generated by Django 5.2.5 on 2025-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0042_alter_query_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
