# Generated by Django 5.2.5 on 2025-10-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0043_reply_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='file',
        ),
        migrations.AddField(
            model_name='msg',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
