# Generated by Django 5.2.5 on 2025-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0044_remove_reply_file_msg_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
