# Generated by Django 5.2.5 on 2025-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0045_reply_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
