# Generated by Django 5.2.5 on 2025-11-29 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0046_conversation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science'), ('AIML', 'Computer Science - Artificial Intelligence & Machine Learning'), ('DS', 'Computer Science - Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MentorMenteeInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
