# Generated by Django 5.2.5 on 2025-11-29 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0047_alter_profile_branch_mentormenteeinteraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentormenteeinteraction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='mentormenteeinteraction',
            name='mentee',
        ),
        migrations.AddField(
            model_name='mentormenteeinteraction',
            name='mentees',
            field=models.ManyToManyField(related_name='mentor_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentormenteeinteraction',
            name='semester',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=10, null=True),
        ),
    ]
