# Generated by Django 5.2.5 on 2025-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0048_alter_mentormenteeinteraction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormenteeinteraction',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
