# Generated by Django 5.2.5 on 2025-12-02 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0049_mentormenteeinteraction_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfileOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_summary', models.TextField(blank=True, help_text='Short professional overview for resume/CV')),
                ('key_skills', models.TextField(blank=True, help_text='Comma separated skills (Python, Django, ML, etc.)')),
                ('achievements_summary', models.TextField(blank=True, help_text='Short summary of achievements')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
