# Generated by Django 5.2.5 on 2025-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0050_studentprofileoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofileoverview',
            name='completeness_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofileoverview',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofileoverview',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofileoverview',
            name='achievements_summary',
            field=models.TextField(blank=True, help_text='Short summary of achievements & awards'),
        ),
    ]
