# Generated by Django 5.2.5 on 2025-12-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0051_studentprofileoverview_completeness_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofileoverview',
            name='achievements_summary',
        ),
    ]
