# Generated by Django 5.2.5 on 2025-12-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0052_remove_studentprofileoverview_achievements_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermgoal',
            name='custom_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='longtermgoal',
            name='plan',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Post Graduation', 'Post Graduation'), ('Entrepreneurship', 'Entrepreneurship'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
