# Generated by Django 5.2.5 on 2025-12-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0055_reminderlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminderlog',
            old_name='auto',
            new_name='is_auto',
        ),
        migrations.RenameField(
            model_name='reminderlog',
            old_name='created_at',
            new_name='last_sent_at',
        ),
        migrations.RemoveField(
            model_name='reminderlog',
            name='resolved',
        ),
    ]
