# Generated by Django 5.2.5 on 2025-12-02 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0056_rename_auto_reminderlog_is_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentormentee',
            name='mentee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_mentor', to='mentee.mentee'),
        ),
    ]
