# Generated by Django 5.2.5 on 2025-12-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0058_reaction_replyseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
