# Generated by Django 6.0 on 2025-12-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0060_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
