# Generated by Django 6.0 on 2025-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0061_activitylog_request_path_alter_activitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
