# Generated by Django 6.0 on 2026-01-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0063_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
