# Generated by Django 6.0 on 2026-01-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0064_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationcourse',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internshippbl',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='otherevent',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paperpublication',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sportsculturalevent',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True),
        ),
    ]
