# Generated by Django 6.0 on 2026-01-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0065_certificationcourse_year_internshippbl_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpublication',
            name='conf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
