# Generated by Django 6.0 on 2026-01-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0066_paperpublication_conf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessment',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=10, null=True),
        ),
    ]
