# Generated by Django 6.0 on 2026-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0067_selfassessment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormenteeinteraction',
            name='ai_summary_generated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
