# Generated by Django 6.0 on 2026-01-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0068_mentormenteeinteraction_ai_summary_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormenteeinteraction',
            name='class_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
