# Generated by Django 6.0 on 2026-01-18 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0069_mentormenteeinteraction_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationcourse',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='internshippbl',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otherevent',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paperpublication',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportsculturalevent',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=20, null=True)),
                ('week', models.CharField(blank=True, choices=[('Week-1', 'Week-1'), ('Week-2', 'Week-2'), ('Week-3', 'Week-3'), ('Week-4', 'Week-4'), ('Week-5', 'Week-5'), ('Week-6', 'Week-6'), ('Week-7', 'Week-7'), ('Week-8', 'Week-8'), ('Week-9', 'Week-9'), ('Week-10', 'Week-10'), ('Week-11', 'Week-11'), ('Week-12', 'Week-12')], max_length=15, null=True)),
                ('year', models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=5, null=True)),
                ('sem', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=5, null=True)),
                ('agenda_file', models.FileField(blank=True, null=True, upload_to='agendas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_agendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-week', '-sem', '-created_at'],
            },
        ),
    ]
