# Generated by Django 6.0 on 2026-01-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0070_alter_certificationcourse_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('CIVIL', 'CIVIL'), ('COMPS', 'COMPUTER SCIENCE'), ('EXTC', 'ELECTRONICS & TELECOMMUNICATION'), ('MECH', 'MECHANICAL'), ('IT', 'INFORMATION TECHNOLOGY'), ('CSE - AIML', 'ARTIFICIAL INTELLIGENCE & MACHINE LEARNING'), ('CSE - DS', 'DATA SCIENCE')], max_length=100, null=True),
        ),
    ]
