# Generated by Django 6.0 on 2026-01-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0071_alter_profile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterresult',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27')], max_length=20, null=True),
        ),
    ]
