# Generated by Django 6.0 on 2026-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0072_semesterresult_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippbl',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
