# Generated by Django 6.0 on 2026-01-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0073_internshippbl_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormenteeinteraction',
            name='last_ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
