# Generated by Django 6.0 on 2026-01-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0074_mentormenteeinteraction_last_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='chat_started',
            field=models.BooleanField(default=False),
        ),
    ]
