# Generated by Django 6.0 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentee", "0075_msg_chat_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationcourse",
            name="qr_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certificationcourse",
            name="qr_payload",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificationcourse",
            name="qr_url_accessible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certificationcourse",
            name="qr_url_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certificationcourse",
            name="verification_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificationcourse",
            name="verification_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificationcourse",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("unverified", "Unverified"),
                    ("manual_verified", "Manual Verified"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
